name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          make install
          npm install
      - name: Build game
        run: make
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/
      # TODO upload the game
